---
- name: Add Docker repository.
  apt_repository:
    repo: "ppa:deluge-team/ppa"
    state: present
    update_cache: true
  tags: [Package Installation]

- name: install deluge
  apt:
    name: "{{ deluge_packages }}"
    state: present
    update_cache: yes
  tags: [Package Installation]

- name: "Configure interfaces and bridge 18.04"
  copy:
    src: deluged.service
    dest: /etc/systemd/system/deluged.service
    owner: root
    group: root
    mode: 0640
    backup: yes
  tags: [Service]

- name: enable and start deluged
  service:
    name: deluged
    state: started
    enable: yes
  tags: [deluged]
