---
- name: Add repo
  command: sudo add-apt-repository ppa:deluge-team/ppa
  tags: [Package Installation]

- name: install deluge
  apt:
    name: "{{ deluge_packages }}"
    state: present
    update_cache: yes
  tags: [Package Installation]

- name: "Configure interfaces and bridge 18.04"
  template:
    src: deluged.service.j2
    dest: /etc/systemd/system/deluged.service
    owner: root
    group: root
    mode: 0640
    backup: yes
  tags: [Service]

- name: enable and start deluged
  service:
    name: deluged
    state: started
    enable: yes
  tags: [deluged]aaaaaaaa
